language: generic
sudo: required
services:
  - docker
script:
  - sudo docker-compose up --build
after_success:
  - docker build -t mfukushima/node-poketeam-container-server-project ./server
  - docker build -t mfukushima/python-poketeam-container-worker-project ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push mfukushima/node-poketeam-container-server-project
  - docker push mfukushima/python-poketeam-container-worker-project