types = [
    {
     "name":"normal",
     "effective":["ghost"],
     "weakness":[]
     },
    {
     "name":"bug",
     "effective":[
        "psychic",
        "ghost",
        "poison",
        "bug",
        "normal",
        "fighting"
        ],
     "weakness":[
        "fire",
        "psychic",
        "fairy"
        ]
    },
    {
     "name":"poison",
     "effective":[
        "grass",
        "fairy",
        "poison",
        "bug",
        "fighting"
        ],
     "weakness":[
         "ground",
         "psychic"
         ]
     },
    {
     "name":"flying",
     "effective":[
        "fighting",
        "bug",
        "grass",
        "ground"
        ],
     "weakness":[
         "eletric",
         "rock",
         "ice"
         ]
     },
    {
     "name":"fire",
     "effective":[
        "bug",
        "steel",
        "ice",
        "grass",
        "bug",
        "fairy"
        ],
     "weakness":[
         "water",
         "ground",
         "rock"
         ]
     },
    {
     "name":"ground",
     "effective":[
        "poison",
        "rock",
        "steel",
        "fire",
        "eletric"
        ],
     "weakness":[
         "water",
         "grass",
         "ice"
         ]
     },
    {
     "name":"fairy",
     "effective":[
        "fighting",
        "dragon",
        "bug"
        ],
     "weakness":[
         "poison",
         "steel"
         ]
     },
    {
     "name":"grass",
     "effective":[
        "ground",
        "water",
        "rock",
        "eletric"
        ],
     "weakness":[
         "fire",
         "flying",
         "poison",
         "bug"
         ]
     },
    {
     "name":"water",
     "effective":[
        "ground",
        "rock",
        "fire",
        "ice",
        "steel"
        ],
    "weakness":[
        "grass",
        "eletric"
        ]
    },
    {
     "name":"fighting",
     "effective":[
        "normal",
        "rock",
        "steel",
        "ice",
        "bug"
        ],
    "weakness":[
        "flying",
        "psychic",
        "fairy"
        ]
    },
    {
     "name":"psychic",
     "effective":[
        "fighting",
        "poison"
        ],
     "weakness":[
         "bug",
         "ghost"
         ]
     },
    {
     "name":"rock",
     "effective":[
        "flying",
        "bug",
        "fire",
        "ice",
        "normal"
        ],
     "weakness":[
         "flying",
         "psychic",
         "fairy"
         ]
     },
    {
     "name":"ghost",
     "effective":[
        "psychic",
        "poison",
        "bug"],
     "weakness":[
        "normal",
        "fighting"
        ]
    },
    {
     "name":"ice",
     "effective":[
        "flying",
        "ground",
        "grass",
        "dragon"
        ],
     "weakness":[
         "fire",
         "rock",
         "fighting",
         "steel"
         ]
     },
    {
     "name":"steel",
     "effective":[
        "rock",
        "ice",
        "fairy",
        "normal",
        "flying",
        "grass",
        "psychic",
        "dragon",
        "bug",
        "poison"
        ],
     "weakness":[
         "fire",
         "ground",
         "fighting"
         ]
     },
    {
     "name":"eletric",
     "effective":[
         "flying",
         "water",
         "steel"
         ],
     "weakness":["ground"]
     },
    {
     "name":"dragon",
     "effective":[
         "dragon",
         "eletric",
         "water",
         "bug",
         "fire"
         ],
     "weakness":[
         "ice",
         "dragon",
         "fairy"
         ]
     }
]